NUMPY 
A hands-on NumPy covering the basics to intermediate concepts of numerical computing with Python.

In [2]:
import numpy as np

In [3]:
list = [1,2,3,4,5]
arr = np.array([list])
arr

array([[1, 2, 3, 4, 5]])

In [4]:
np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
np.random.rand(5)

array([0.23358782, 0.3205596 , 0.51211099, 0.2512816 , 0.20167727])

In [9]:
np.random.randn(5)

array([ 0.47971856, -1.37255863, -0.27192721,  1.60597906, -0.86502474])

In [10]:
arr = np.random.randint(12,24,3)
arr

array([17, 13, 16])

In [11]:
arr = np.arange(1,19).reshape(3,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [12]:
arr.shape

(3, 6)

In [13]:
arr.size

18

In [14]:
arr.max()

18

In [15]:
arr.min()

1

In [16]:
arr.mean()

9.5

In [17]:
np.sum(arr,axis =1)

array([21, 57, 93])

In [18]:
arr.argmin()

0

In [19]:
arr.argmax()

17

In [20]:
arr = np.arange(29,49)
arr

array([29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48])

In [21]:
arr[4]

33

In [22]:
arr[3:8]

array([32, 33, 34, 35, 36])

In [23]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [25]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [27]:
arr[1:4,1:3]

array([[ 8,  9],
       [14, 15],
       [20, 21]])

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
sum = arr1+arr2
sum

array([ 7,  9, 11, 13, 15])

In [29]:
slice=arr1[1:5]
okay = slice*10
okay

array([20, 30, 40, 50])

In [30]:
arr3 = arr1.copy()

In [31]:
arr3[0]=5

In [32]:
arr3

array([5, 2, 3, 4, 5])

In [33]:
arr1

array([1, 2, 3, 4, 5])

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
e = np.column_stack((a,b))
e

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [39]:
g = np.arange(1,31).reshape(5,6)
g

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [41]:
f = np.hsplit(g,6)
f

[array([[ 1],
        [ 7],
        [13],
        [19],
        [25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3],
        [ 9],
        [15],
        [21],
        [27]]),
 array([[ 4],
        [10],
        [16],
        [22],
        [28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]]),
 array([[ 6],
        [12],
        [18],
        [24],
        [30]])]

In [ ]:
f = np.vsplit(g,6)
f

sudoku

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
add = np.sum(s,axis = 1)
for i in add:
    if i != 45:
        print("sudoko is not valid")
else:
    print("done from row side")

In [ ]:
add = np.sum(s,axis = 0)
for i in add:
    if i != 45:
        print("sudoko is not valid")
else:
    print("done from column side")

In [ ]:
q =s[:3,:3]
q

In [ ]:
q.sum()

In [43]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Get the shape of the matrix.

In [46]:
data.shape

(5, 3)

Find the average age of students.

In [49]:
age = data[0:,0:1]

In [51]:
avg = age.mean()
avg

18.4

Extract Math marks of all students.

In [54]:
maths_marks = data[:,1]
maths_marks

array([85, 92, 76, 65, 90])

In [56]:
#Find the highest Science mark.
science_marks = data[:,2]
np.max(science_marks)

95

In [58]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [60]:
#Increase Math marks of all students by 5.
increse_marks = data[:,1]+5
increse_marks

array([90, 97, 81, 70, 95])

In [62]:
#Find how many students are younger than 19.˘
len(data[data[:,0]>19])


1

In [64]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [66]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80)&(data[:,1] >=80)]

array([[18, 85, 78],
       [19, 92, 88],
       [20, 90, 85]])

In [87]:
#Replace all Science marks < 75 with 0.
data[:,2:][data[:,2:]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])